CREATE TABLE [dbo].[Url]
(
	[Id]					BIGINT NOT NULL IDENTITY PRIMARY KEY,
	[Code]					VARCHAR(10) NOT NULL UNIQUE,
	[Created]				DATETIME2(3) NOT NULL DEFAULT GETDATE(),
	[DomainId]              BIGINT NOT NULL,
	[UrlOriginal]			VARCHAR(1000) NOT NULL,
	CONSTRAINT			    [FK_Url_DomainId] FOREIGN KEY ([DomainId]) REFERENCES Domain([Id])
)
